name: Deploy React App to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:  # Define inputs for manual runs
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }} # Use the selected branch or the push branch

      # Set up Node.js to build the React app
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies and build the React app
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build
