name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Node.js to build the React app
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies and build the React app
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      # Configure SSH key for deployment
      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Copy build files to the EC2 instance
      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_IP: ${{ secrets.EC2_IP }}
          APP_DIR: ${{ secrets.APP_DIR }}
        run: |
          # Ensure the app directory exists on the EC2 instance
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP "mkdir -p $APP_DIR"
          
          # Copy build files to the EC2 instance
          scp -o StrictHostKeyChecking=no -r build/* $EC2_USER@$EC2_IP:$APP_DIR

      # Restart Nginx or any other server if needed
      - name: Restart Server (Optional)
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_IP: ${{ secrets.EC2_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP "sudo systemctl restart nginx"
